---
version: 2
plan:
  project-key: SP
  key: EMAILLAMBDA
  name: Build the email-lambda

# List of plan's stages and jobs
stages:
  - Test the email lambda stage:
      jobs:
        - Test
  - Build The Native Image:
      jobs:
        - Build

#Job definition
Test:
  tasks:
    - script:
        - mvn test
    - test-parser:
        type: junit
        test-results: '**target/surefire-reports/*.xml'
  # Job's requirements
  requirements:
    - JDK
    - MVN

Build:
  tasks:
    - script:
        - mvn package -DskipTests -Dnative -Dquarkus.native.container-build=true
  # Job's artifacts. Artifacts are shared by default.
  artifacts:
    - name: Native Executable
      pattern: target/email-lambda-1.0-SNAPSHOT-runner
    - name: Zipped Function
      pattern: target/function.zip
  # Job's requirements
  requirements:
    - Docker
    - JDK
    - MVN
