---
version: 2
plan:
  project-key: SP
  key: EMAILLAMBDA
  name: Build the email-lambda

# List of plan's stages and jobs
stages:
  - Build the rocket stage:
      - Build

#Job definition
Build:
  tasks:
    - script:
        - mvn package
    - test-parser:
        type: junit
        test-results: '**target/surefire-reports/*.xml'
  # Job's requirements
  requirements:
    - Docker
    - JDK
    - MVN
  # Job's artifacts. Artifacts are shared by default.
  artifacts:
    - name: Packaged Uber JAR
      pattern: target/email-lambda-1.0-SNAPSHOT-runner.jar
    - name: Zipped Function
      pattern: target/function.zip